// SelectTopics.js

import React from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet } from 'react-native';
import { useNavigation } from '@react-navigation/native';

const topics = [
  'abiotic',
  'active transport',
  'adaptation',
  'aerobic bacteria',
  'alimentary canal',
  'allele',
  'allopatric speciation',
  'amphipathic',
  'anabolism',
  'anaerobic',
  'anaerobic respiration',
  'analogous',
  'analogous structures',
  'anatomy',
  'angiosperm',
  'animal',
  'animal cell',
  'antagonistic muscle',
  'antigen',
  'apoenzyme',
  'asexual reproduction',
  'assimilation',
  'autocrine signaling',
  'autotroph',
  'axon hillock',
  'axon terminal',
  'bacteria',
  'balanced diet',
  'base-pairing rule',
  'benign',
  'biennial',
  'binary fission',
  'binomial nomenclature',
  'biodiversity',
  'biological system',
  'biology',
  'biome',
  'biosphere',
  'biotic',
  'biotic factor',
  'biotic potential',
  'biuret test',
  'bivalent',
  'body fluid',
  'bolus injection',
  'bone matrix',
  'book lungs',
  'botany',
  'buck’s traction',
  'budding',
  'carbon fixation',
  'carrier protein',
  'carrying capacity',
  'cell',
  'cell morphology',
  'cell wall',
  'cellular respiration',
  'chemiosmosis',
  'chloroplast',
  'chordata',
  'chromatin',
  'chromosomal mutation',
  'chromosome',
  'class',
  'codominance',
  'codon',
  'coenzyme',
  'cohesion',
  'commensalism',
  'complete dominance',
  'concentration gradient',
  'condyloid joint',
  'convergent evolution',
  'convoluted',
  'coronavirus COVID-19',
  'cross-linking',
  'cytokinesis',
  'cytoplasm',
  'darwinian fitness',
  'deciduous forest',
  'decomposer',
  'definitive host',
  'dehydration reaction',
  'demographic transition',
  'dense irregular connective tissue',
  'dense regular connective tissue',
  'density-dependent factor',
  'density-dependent limiting factor',
  'deoxyribonucleic acid',
  'desiccation',
  'diaphoresis',
  'diarthrodial joint',
  'dichotomous',
  'differentiation',
  'diffusion',
  'diploid',
  'disruptive selection',
  'divergent evolution',
  'dominant',
  'dominant species',
  'ecological niche',
  'ecosystem',
  'ecosystem diversity',
  'element',
  'endemic',
  'endocytosis',
  'endomembrane system',
  'endosymbiosis',
  'endosymbiotic theory',
  'energy coupling',
  'environment',
  'environmental resistance',
  'epidermis',
  'epistasis',
  'equilibrium',
  'eukaryote',
  'eukaryotic cells',
  'evolution',
  'exon',
  'exotic species',
  'exudate',
  'facilitated diffusion',
  'facultative anaerobe',
  'family',
  'family traits',
  'fastidious',
  'fecundity',
  'feedback mechanism',
  'female',
  'fermentation',
  'fibrinous exudate',
  'fibrocartilage',
  'filtration',
  'first-order kinetics',
  'fitness',
  'flaccid',
  'flora',
  'fluid mosaic model',
  'focus',
  'follicle-stimulating hormone',
  'fragmentation',
  'frameshift mutation',
  'fundamental niche',
  'fungi',
  'gamete',
  'ganglia',
  'gene',
  'genetic diversity',
  'genetic drift',
  'genetic material',
  'genetics',
  'genome',
  'genotype',
  'genotypic ratio',
  'genus',
  'glucose',
  'glycerol',
  'glycogenolysis',
  'glycolipid',
  'glycolysis',
  'golgi apparatus',
  'graded potential',
  'gram-positive bacilli',
  'gram-positive cocci',
  'group translocation',
  'growth',
  'guanine',
  'haploid',
  'heredity',
  'hermaphrodite',
  'heterotroph',
  'heterozygous',
  'homeostasis',
  'homo sapiens sapiens',
  'homogeneous',
  'homologous',
  'homologous chromosome',
  'homologous structures',
  'homozygous',
  'host cell',
  'hyaline cartilage',
  'hydrophilic',
  'hydrophobic',
  'hyperosmotic',
  'hypersensitivity',
  'hypertonic',
  'hypomelanism',
  'hypothesis',
  'hypotonic',
  'hypotonic solution',
  'hypotonicity',
];

const SelectTopics = () => {
  const navigation = useNavigation();

  const handleTopicSelection = (topic) => {
    navigation.navigate('StartQuiz', { selectedTopic: topic });
  };

  return (
    <View style={styles.container}>
      <Text style={styles.headerText}>Select Topics</Text>
      <ScrollView style={styles.scrollContainer}>
        {topics.map((topic) => (
          <TouchableOpacity
            key={topic}
            style={styles.topicItem}
            onPress={() => handleTopicSelection(topic)}
          >
            <Text style={styles.topicText}>{topic}</Text>
          </TouchableOpacity>
        ))}
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    alignItems: 'center',
  },
  headerText: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  scrollContainer: {
    width: '100%',
  },
  topicItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  topicText: {
    fontSize: 16,
  },
});

export default SelectTopics;
